version: "3.7"

services:
  mariadb:
    image: $MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USERw
      - "3306:3306"
    volumes:
      - ./db/mysql:/var/lib/mysql
#      - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql

networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.51.0/24